apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
    app: nginx
spec:
  project: default
  
source:
  repoURL:  https://github.com/wolexbuk/helm-class.git
  targetRevision: HEAD
desination:
  server: https://kubernetes.default.svc  
  namespace: myapp  

syncPolicy:
   synOptions:
   - CreateNamespace=true  

   automated:
     selfHeal: true
     prune: true